name: 'LDCHECK-action'
description: 'Run LDCHECK on Android recovery builds'
inputs:
  OUTPUT_DIR:
    default: ''
    description: 'Output directory of the build'
    required: true
  LDCHECKPATH:
    description: 'Path of blobs to check'
    required: true
    default: 'system/bin/qseecomd'
steps:
  - name: Run LDCheck
    run: |
      # Determine the output directory, use env.OUTPUT_DIR if inputs.OUTPUT_DIR is not provided
      OUTPUT_DIR="${{ inputs.OUTPUT_DIR }}"
      if [ -z "$OUTPUT_DIR" ]; then
        OUTPUT_DIR="${{ env.OUTPUT_DIR }}"
      fi
      
      # Copy tools to the appropriate location
      cp ${{ github.action_path }}/tools/ldcheck "$OUTPUT_DIR/recovery/root/"
      
      # Change to the recovery root directory
      cd "$OUTPUT_DIR/recovery/root"
      
      # Run ldcheck
      python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
      echo "Done checking missing dependencies. Review, and reconfigure your tree."
    shell: bash
    continue-on-error: true


branding:
  icon: terminal
  color: green
