name: 'LDCHECK'
description: 'Run LDCHECK on Android recovery builds'
inputs:
  OUTPUT_DIR:
    description: 'Output directory of the build'
    required: true
  DEVICE_NAME:
    description: 'Device Codename'
    required: true
  LDCHECKPATH:
    description: 'Path of blobs to check'
    required: true
    default: 'system/bin/qseecomd'

runs:
  using: "composite"
  steps:
    - name: Run LDCheck
      run: |
        # Copy tools to the appropriate location
        cp ${{ github.action_path }}/tools/libneeds ${{ inputs.OUTPUT_DIR }}/${{ inputs.DEVICE_NAME }}/recovery/root/
        cp ${{ github.action_path }}/tools/ldcheck ${{ inputs.OUTPUT_DIR }}/${{ inputs.DEVICE_NAME }}/recovery/root/
        
        # Change to the recovery root directory
        cd ${{ inputs.OUTPUT_DIR }}/${{ inputs.DEVICE_NAME }}/recovery/root
        
        # Run ldcheck
        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
        echo "Done checking missing dependencies. Review, and reconfigure your tree."
      shell: bash
      continue-on-error: true

branding:
  icon: terminal
  color: green
